#!/system/bin/busybox sh

echo "shutdown" > /sys/android_power/acquire_partial_wake_lock

stop;
stop dhcpcd;

sleep 1;

while read DEV DIR FS OPTS X Y;
do
busybox mount -o remount,ro $DIR 2>&1 > /dev/null;
done < /proc/mounts

sync;

if [ "$1" = "-r" ];
then
toolbox reboot;
else
toolbox reboot -p;
fi
